#!/usr/bin/env bash

#Setting variables
RESPAWN_DIR=$HOME/.config/respawn
FISH=$(which fish)
BASH=$(which bash)
ZSH=$(which zsh)
SALT=$(which salt-call)

    
#Presenting a platform specific help menu
function help() {
    echo "~~~~ $OSTYPE ~~~~"
    echo "$0 accepts the following commands:"
        echo "---- "
        echo "-h | --help (This help menu!!!)"
        echo "-g | --go (run the Salt high state)"
        echo "-s | --saltcall blah... (runs a salt call with up to 3 arguments)"
        echo "-S | This switches respawn origin to ssh. Use this when you have an SSH key for respawn"
        echo "-H | This switches respawn origin to HTTPS. Use this if you only have a passcode"
}

# Finding salt installation and setting variable
SALT=$(which salt-call)
# Salt call with Pillar data
function sc_p() {
    sudo "$SALT" \
        --config-dir="${RESPAWN_DIR}" \
        $salt_command $arg_1 $arg_2 $arg_3 \
        pillar="{'user': '$USER', 'home': '$HOME', 'bash': '$BASH', 'respawn_dir': '$RESPAWN_DIR', 'respawn': '$RESPAWN_DIR/respawn', zim': '$ZIM_HOME', 'zsh': '$ZSH', 'secrets_dir': '$RESPAWN_DIR/secrets'}" 
}
# Salt call without Pillar data, because some commands don't like it (i.e. grains)
function sc() {
    sudo "$SALT" \
        --config-dir="${RESPAWN_DIR}" \
        $salt_command $arg_1 $arg_2 $arg_3
}

case "$1" in
    # Display help to user
    "-h" | "--help")
    help
    ;;

    #Salt command
    "-s" | "--salt")
    salt_command=$2
    arg_1=$3
    arg_2=$4
    arg_3=$5
    if [[ $2 == "grains.items" ]] ; then
      sc
    else
      sc_p
    fi
    ;;

    #Salt highstate
    "-g" | "--go")
    salt_command="state.apply"
    arg_1=""
    sc_p

        if [[ $(echo $SHELL) != $ZSH ]]; then
            $ZSH
        fi
        ;;
    
    #Switch to respawn origin to ssh
    "-S" | "ssh_auth--")
    git remote set-url origin git@github.com:jRob2k/respawn.git 
    echo "respawn remote origin updated for SSH auth"
    ;;
     
    #Switch to respawn origin to ssh
    "-H" | "http_auth--")
    git remote set-url origin https://github.com/jRob2k/respawn.git 
    echo "respawn remote origin updated for HTTP auth"
    ;;
    
    #Launch help
    *)
    help
    ;;
esac

