#!/usr/bin/env bash

#Setting variables
RESPAWN_DIR=$HOME/.config/respawn
FISH=$(which fish)
BASH=$(which bash)
ZSH=$(which zsh)
SALT=$(which salt-call)

    
#Presenting a platform specific help menu
function help() {
    echo "~~~~ $OSTYPE ~~~~"
    echo "$0 accepts the following commands:"
        echo "---- "
        echo "-h | --help (This help menu!!!)"
        echo "-g | --go (run the Salt high state)"
        echo "-s | --salt <state> (runs one state instead of the entire highstate)"
}

# Finding salt installation and setting variable
SALT=$(which salt-call)
function sc() {
    # Temporarily changing default shell so that salt calls in respawn will work. 
    # TODO: This isn't quite working. Somewhere the space between shell and user is getting removed so it's trying to change to $shell$user instead of just $shell
    # TODO: Figure out why it doesn't work with fish shell and fix
    
    # ORIGINALSHELL=$SHELL
    # if [[ $SHELL == $FISH ]]; then
    #         sudo chsh -s $(which bash) $USER
    # fi
    sudo "$SALT" \
        --config-dir="${RESPAWN_DIR}" \
        $salt_command $state $flag_1 $option_1 \
        pillar="{'user': '$USER', 'home': '$HOME', 'fish': '$FISH', 'bash': '$BASH', 'zsh': '$ZSH', 'secrets_dir': '$RESPAWN_DIR/secrets'}" 

    # Change default shell back to FISH if it was FISH
    # if [[ $ORIGINALSHELL != $SHELL ]]; then
    #     sudo chsh -s $ORIGINALSHELL $USER
    # fi
}


case "$1" in
    # Display help to user
    "-h" | "--help")
    help
    ;;

    #Salt states
    "-s" | "--salt")
    salt_command="state.apply"
    state=$2
    flag_1=$3
    option_1=$4
    sc
    ;;

    #Salt highstate
    "-g" | "--go")
    salt_command="state.apply"
    state=""
    sc

        # Launch fish if it's not already the shell.
	# TODO: Should i change this to just be "prefered shell" or something instead of hardcoding fish?
        if [[ $(echo $SHELL) != $FISH ]]; then
            $FISH
        fi
        ;;

    #Launch help
    *)
    help
    ;;
esac

